recipe: default.v1
language: zh

pipeline:
- name: MitieNLP #训练词向量的组件
  model: data/total_word_feature_extractor_zh.dat #词向量矩阵
- name: JiebaTokenizer #分词、token组件
  dictionary_path: data/jieba_userdict #分词后的字典
- name: MitieEntityExtractor #实体识别组件
- name: EntitySynonymMapper
- name: RegexFeaturizer #模式匹配组件
- name: MitieFeaturizer #特征提取组件
- name: SklearnIntentClassifier
#- name: DIETClassifier #意图识别组件（文本分类）
#  entity_recognition: false
#  epochs: 50


policies:
#- name: "TEDPolicy"
#  epochs: 50
#- name: "MemoizationPolicy"
#  max_history: 5
#- name: "RulePolicy"
- name: TEDPolicy
  epochs: 120
  featurizer:
  - name: MaxHistoryTrackerFeaturizer
    max_history: 5
    state_featurizer:
    - name: BinarySingleStateFeaturizer
- name: rasa.core.policies.memoization.MemoizationPolicy
  max_history: 5
- name: rasa.core.policies.mapping_policy.MappingPolicy
- name: rasa.core.policies.fallback.FallbackPolicy
  nlu_threshold: 0.4
  core_threshold: 0.3
  fallback_action_name: action_donknow

# featurizer:
# - name: MaxHistoryTrackerFeaturizer
#   max_history: 5
#   state_featurizer:
#   - name: BinarySingleStateFeaturizer
# - name: "FallbackPolicy"
#   nlu_threshold: 0.4
#   core_threshold: 0.3
#   fallback_action_name: action_donknow
